### PR TITLE
Add more initial guess for acrobot swing up

### PR DESCRIPTION
**Pull request by hongkai-dai**

### CODE REVIEW

**Comment by RussTedrake** [comment]
Thanks @hongkai-dai .  Everything in this program/solver should be deterministic, right?  So I don't see why we need to loop through three initial conditions.  Presumably one of them is working (every time)?

**Comment by hongkai-dai** [comment]
That's definitely right, that one of the initial guess should work for this deterministic test. I added this PR because when we change our `SnoptSolver` in drake, the initial guess that worked before, doesn't work any more. The same thing happens when we upgrade to snopt 7.6. So I thought we can try several initial guesses, to avoid the solver getting stuck at a local minima, when there is some change on the solver (either the snopt upstream code, or our SnoptSolver wrapper).

I can also just use one initial guess, that works for the current implementation of SnoptSolver and upstream snopt 7.2, if you think that is a better solution.

**Comment by hongkai-dai** [comment]
I switched back to the original initial guess, but with additional bounds on the duration.

**Comment by hongkai-dai** [comment]
The same test passes on my machine, but fails on CI. I guess the drake version is not the same? In this PR, `dircol_swingup` succeeds with the up-to-date drake, but fails if drake is before the revision 770daa6d

**Comment by RussTedrake** [comment]
tweaked this and closing it (to update it alongside the drake sha.  thanks!)

**Pull request closed without merging**
