### PR TITLE
Meshcat Rigid Body Visualizer

### PR DESCRIPTION
**Pull request by gizatt**
Usage: after grabbing meshcat from pip, `meshcat-server` should be available as a terminal command. Run that, and verify that you can go to the reported web url to see the visualizer. Then running this example (e.g. `python meshcat_rigid_body_visualizer.py -m val` should show an animation in the browser window.)

I hacked in the zmq / meshcat dependency (and hope it'll work for the CI) -- open to suggestions on better / other ways this could be made useful.

### CODE REVIEW

**Comment by RussTedrake** [comment]
you didn't add the visualizer to the CMakeLists.txt, so it's not being tested / linted by CI?  

can't wait to try this.

**Comment by RussTedrake** [comment]
could you add the usage note to the meshcat_visualizer.py or the README.md?  (probably prefer the .py?)

**Comment by RussTedrake** [comment]
it works!  but I definitely see some flipped normals in my val visualization. 
cc @rdeits 

screen shot 2018-04-18 at 3 52 22 pm

**Comment by RussTedrake** [comment]
(and no texture maps?)

**Comment by rdeits** [comment]
The flipped normals are caused by actual problems with the `.obj` files in Drake: https://github.com/RobotLocomotion/drake/issues/8130

MeshCat does support textures, but you have to explicitly pass the texture file path in the material, as in the `head_multisense.obj` example from https://github.com/rdeits/meshcat-python/blob/master/demo.ipynb 

We didn't have this problem with Director/DrakeVisualizer because Director actually cheats: when you tell it to load a `.obj` file, it actually loads a file with the same name but a different extension (either .dae or .vtp, I can't remember), and those files contain the texture map in the mesh file itself (and don't happen to have their normals inverted on the left side).

**Comment by gizatt** [comment]
Sorry to delay! I'd like to get texture support in but didn't want to bite it off quite yet... and would have to investigate how hacky it would be, given the only-partial support for textures in Drake. A middle ground might be at least getting some color support to add some contrast / interest to the renderings?

**Pull request merged**
