### PR TITLE
add input limits to test and notebook for closed loop controller

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/476)

### CODE REVIEW

**Comment by RussTedrake** [comment]
___
*[underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py, line 94 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7tiq2ExaIleH2nYoA:-Mx7tiq2ExaIleH2nYoB:b-43cxfz) ([raw file](https://github.com/russtedrake/underactuated/blob/5b92919a767aa3b8cf08a55092f1d28aadeae916/underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py#L94)):*
> ```Python
>         """Test policy"""
>         value_mlp = self.notebook_locals['value_mlp']
>         input_limits = self.notebook_locals['input_limits']
> ```

you saw my previous comment about how this is a bit risky?  (students can change the input limits and impact the grader?)

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/476)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice and @RussTedrake)

___
*[exercises/dp/pendulum_cvi.ipynb, line 656 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7u2Ye3SbP5kg4V0M2:-Mx7u2Ye3SbP5kg4V0M3:b-d39g3k) ([raw file](https://github.com/russtedrake/underactuated/blob/4112491a808a9a82a31d490c953702cf2f4ade1b/exercises/dp/pendulum_cvi.ipynb#L656)):*
> ```
>     "            if self.input_limits != None:\n",
>     "                ui = np.minimum(np.maximum(ui, self.input_limits[0]),\n",
>     "                                self.input_limits[1])\n",
> ```

why remove this?  you're passing in the input_limits but not using them?
___
*[underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py, line 215 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7txki49j6_F0RisP2:-Mx7txki49j6_F0RisP3:b-uflnoa) ([raw file](https://github.com/russtedrake/underactuated/blob/4112491a808a9a82a31d490c953702cf2f4ade1b/underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py#L215)):*
> ```Python
>             if self.input_limits is not None:
>                 ui = np.minimum(np.maximum(ui, self.input_limits[0]),
>                                 self.input_limits[1])
> ```

i don't understand why you're removing this??

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/476)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @RussTedrake)

___
*[exercises/dp/pendulum_cvi.ipynb, line 656 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7u2Ye3SbP5kg4V0M2:-Mx9Y-_P8Kf_lynvR3lP:b-kdfp) ([raw file](https://github.com/russtedrake/underactuated/blob/4112491a808a9a82a31d490c953702cf2f4ade1b/exercises/dp/pendulum_cvi.ipynb#L656)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why remove this?  you're passing in the input_limits but not using them?
</blockquote></details>

These lines here are for computing dstate_dynamics_du. In the next line we compute u_star and then clip the dynamics.
___
*[underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py, line 94 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7tiq2ExaIleH2nYoA:-Mx9YPiHDq2_sqoH1RCh:bv0i8hc) ([raw file](https://github.com/russtedrake/underactuated/blob/5b92919a767aa3b8cf08a55092f1d28aadeae916/underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py#L94)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

you saw my previous comment about how this is a bit risky?  (students can change the input limits and impact the grader?)
</blockquote></details>

Students can change the input limits, but this way if someone does but their network implementation is correct the grader will test the network implementation. We often have values students shouldn't change in the grader, but if in a future iteration a TA wants to change the input limits they won't have to double change the test as well
___
*[underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py, line 215 at r1](https://reviewable.io/reviews/russtedrake/underactuated/476#-Mx7txki49j6_F0RisP2:-Mx9YIAp0zHSM3uu2j51:bii95s3) ([raw file](https://github.com/russtedrake/underactuated/blob/4112491a808a9a82a31d490c953702cf2f4ade1b/underactuated/exercises/dp/pendulum_cvi/test_pendulum_cvi.py#L215)):*
> These lines here are for computing dstate_dynamics_du. In the next line we compute u_star and then clip the dynamics.

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/476#-:-Mx9pwh361ZpqNGSoNVq:bnfp4nl)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @RussTedrake)

**Pull request merged**
