### PR TITLE
[WIP] symbolic: Workaround for numpy#10876

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates https://github.com/RobotLocomotion/drake/pull/8452

This works around numpy/numpy#10876 (numpy/numpy#9028) by explicitly using `Expression` with `np.dot`, since `np.dot` cannot be used with `Variable` as it is not closed under addition / subtraction.

This should be merged in if/when the above Drake PR lands.

This passes locally on my machine when using the following PR commit for NumPy: https://github.com/numpy/numpy/pull/10898

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/113)

### CODE REVIEW

**Comment by RussTedrake** [comment]
my normal visibility on github notifications is severely crippled this week.  please feel free to ping me when the prereqs are met.  thanks!

**Comment by RussTedrake** [comment]
@EricCousineau-TRI -- what's the current state of this one?

**Comment by EricCousineau-TRI** [comment]
Still dependent on RobotLocomotion/drake#8452; I've not put much effort behind it aside from maybe 2 hrs in the past few months.

Want me to try and get that merged in?

**Comment by RussTedrake** [comment]
not urgent for me.  just making sure the PR is not obsolete.

**Pull request closed without merging**
