### PR TITLE
Added fitted double integrator exercise

### PR DESCRIPTION
**Pull request by echen9898**
* Updated dp textbook chapter with exercise listing

* Added exercise notebook

* Added exercise autograder test file

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418)* status: all files reviewed, 7 unresolved discussions (waiting on @echen9898)

___
*[dp.html, line 1002 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrw9Mv7UsC1l1xx78u:-MUrw9Mv7UsC1l1xx78v:b-k72pht) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1002)):*
> ```HTML
>     <exercise><h1>Fitted Value Iteration for the Double Integrator</h1>
> 
>       <p>In this exercise we will implement fitted value iteration with a neural network, and use it to generate a controler for the double integrator.  <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb" target="_blank">In this python notebook</a>, you will need to implement a few things.  Take the time to go through the notebook and understand the code in it, and then answer the following questions.  The written questions will also be listed in the notebook for your convenience.</p>
> ```

controler => controller 

The exercise seems to ignore the existence of the “neural value iteration” example above.  how do the two relate?
___
*[dp.html, line 1008 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwUC-5biAqpDXN0Na:-MUrwUC-5biAqpDXN0Nb:ba0s4f3) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1008)):*
> ```HTML
>         <li>Work through the coding sections in <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb" target="_blank">this python notebook</a>.</li>
> 
>         <li>Although it gets close, in <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb" target="_blank">this python notebook</a> why does our implementation not succeed in stabilizing the system exactly at the origin?</li>
> ```

it’s a little strange to link to the same notebook again here this way, when it’s obviously the same one you linked to just above?
___
*[dp.html, line 1010 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwkJO5qWtBp_5J2Jf:-MUrwkJO5qWtBp_5J2Jg:bl3ubk6) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1010)):*
> ```HTML
>         <li>Although it gets close, in <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb" target="_blank">this python notebook</a> why does our implementation not succeed in stabilizing the system exactly at the origin?</li>
> 
>         <li>In this notebook we implemented "fitted value iteration".  In terms of the problem setting, why would we use "fitted value iteration" instead of graph search?  By problem setting we mean: discrete/continuous states, discrete/continuous actions, discrete/continuous time.</li>
> ```

the question is pretty open-ended (which is fine), but know that you’ll get a huge variety of answers for it.  maybe ask something a little more specific?
___
*[dp.html, line 1012 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwvPM53wOuN_Hidy4:-MUrwvPM53wOuN_Hidy5:b-2lhmxl) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1012)):*
> ```HTML
>         <li>In this notebook we implemented "fitted value iteration".  In terms of the problem setting, why would we use "fitted value iteration" instead of graph search?  By problem setting we mean: discrete/continuous states, discrete/continuous actions, discrete/continuous time.</li>
> 
>         <li>For our implementation, we assume deterministic transitions between states.  This means that given a particular state $x_t$ and action $u_t$, we will always end up in the same unique $x_{t+1}$.  Mathematically: $$x_{t+1} = f(x_t, a_t)$$  In real world scenarios we often have to deal with things like noisy actuation, which can cause our state transitions to be stochastic.  Mathematically: $$P(x_{t+1} | x_t, a_t) = f(x_t, a_t)$$  If we had stochastic transitions, which step of the algorithm would need to change, and how would it change?</li>
> ```

a_t => u_t

i don’t actually believe in “noisy actuation”.  that’s something people say, but it doesn’t really parse for me.  i think sensor noise is real (but not relevant here).  the reason for the dynamics being stochastic is more about disturbances or unmodelled dynamics.
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 123 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs-Z1V9XZ4w7aW-wZZ:-MUs-Z1V9XZ4w7aW-wZ_:b-ca0s9r) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L123)):*
> ```
>     "        \n",
>     "class DoubleIntegratorVisualizer(PyPlotVisualizer):\n",
>     "\n",
> ```

i guess you copied this code in from the .py file?  (why not just use the .py?). if the goal is to make them look at it, i think we can probably put a link to the file instead?
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 463 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0G7t5YGiEWlD1R1Z:-MUs0G7t5YGiEWlD1R1_:bkh8jb8) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L463)):*
> ```
>     "    \n",
>     "    state_grid = [set(x1s.data.numpy()), set(x2s.data.numpy())]\n",
>     "    state_mesh = BarycentricMesh(state_grid)\n",
> ```

why do you need/want the barycentric mesh here?  you can just evaluate [g(x,u) + gamma*J(xnext)] using the neural net directly for each u and pick the best?  
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 599 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0jNX-m7R2T9RRvvv:-MUs0jNY1oUgp5g7bjeh:byh4kac) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L599)):*
> ```
>     "$$x_{t+1} = f(x_t, a_t)$$\n",
>     "\n",
>     "In real world scenarios we often have to deal with things like noisy actuation, which can cause our state transitions to be stochastic. Mathematically:\n",
> ```

i guess all of my comments above still apply here.

**Review by echen9898 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418)* status: all files reviewed, 7 unresolved discussions (waiting on @RussTedrake)

___
*[dp.html, line 1002 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrw9Mv7UsC1l1xx78u:-MUsWUh_1gt-goi7wDYw:bmmufer) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1002)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

controler => controller 

The exercise seems to ignore the existence of the “neural value iteration” example above.  how do the two relate?
</blockquote></details>

Yeah I mentioned this in the chat yesterday - I was thinking of folding the two in together and having it either be an exercise or a textbook example? Or else it seems roundabout to have them work through the first part, or do a completely rewrite.
___
*[dp.html, line 1008 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwUC-5biAqpDXN0Na:-MUsXvkk-IelYNuZmsCr:b-hfghm4) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1008)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it’s a little strange to link to the same notebook again here this way, when it’s obviously the same one you linked to just above?
</blockquote></details>

Sounds good
___
*[dp.html, line 1010 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwkJO5qWtBp_5J2Jf:-MUsYR_b4SOOPTHRxVHZ:b-tyk497) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1010)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the question is pretty open-ended (which is fine), but know that you’ll get a huge variety of answers for it.  maybe ask something a little more specific?
</blockquote></details>

Yeah I got a question in OH about this and just want to highlight discrete vs continuous state - I'll reword.
___
*[dp.html, line 1012 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwvPM53wOuN_Hidy4:-MUsY8-zAkx6cj03ACxD:b-5omsrc) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1012)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

a_t => u_t

i don’t actually believe in “noisy actuation”.  that’s something people say, but it doesn’t really parse for me.  i think sensor noise is real (but not relevant here).  the reason for the dynamics being stochastic is more about disturbances or unmodelled dynamics.
</blockquote></details>

Got it - will update
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 123 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs-Z1V9XZ4w7aW-wZZ:-MUsYhlt4WylgHPJNwL6:b-gufvwh) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L123)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i guess you copied this code in from the .py file?  (why not just use the .py?). if the goal is to make them look at it, i think we can probably put a link to the file instead?
</blockquote></details>

I changed a few things - the .py file wasn't animating for me. I needed to pass in the ax/show arguments to PyPlotVisualizer and left this in.
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 463 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0G7t5YGiEWlD1R1Z:-MUs_1Go993Kmar0x_wg:bsc1clk) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L463)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why do you need/want the barycentric mesh here?  you can just evaluate [g(x,u) + gamma*J(xnext)] using the neural net directly for each u and pick the best?  
</blockquote></details>

Yeah I was debating this - I liked the mesh in terms of just exposing them to another drake system they can look up to get used to the docs. Using the nn directly is cleaner/more efficient and we could axe this
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 599 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0jNX-m7R2T9RRvvv:-MUs_QnUBuvyoYeSJFuc:byppow9) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L599)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i guess all of my comments above still apply here.
</blockquote></details>

Yup - will fix both versions.

**Review by echen9898 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418)* status: all files reviewed, 7 unresolved discussions (waiting on @RussTedrake)

___
*[dp.html, line 1008 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwUC-5biAqpDXN0Na:-MUsbtVb-SdbfgtgeIZ8:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1008)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.
___
*[dp.html, line 1010 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwkJO5qWtBp_5J2Jf:-MUsbnsm2V_sa8Q9q9Bf:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1010)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Yeah I got a question in OH about this and just want to highlight discrete vs continuous state - I'll reword.
</blockquote></details>

Done.
___
*[dp.html, line 1012 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwvPM53wOuN_Hidy4:-MUsbvr37ZnftQWxcDmA:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1012)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Got it - will update
</blockquote></details>

Done.
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 599 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0jNX-m7R2T9RRvvv:-MUsc2B33X9SQw5oEKgC:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L599)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Yup - will fix both versions.
</blockquote></details>

Done.

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418)* status: all files reviewed, 4 unresolved discussions (waiting on @echen9898 and @RussTedrake)

___
*[dp.html, line 1010 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUrwkJO5qWtBp_5J2Jf:-MUtv4hr7ux3y9aUjShH:b-109uaa) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/dp.html#L1010)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

are you simply trying to ask them "does this work for discrete states?  continuous states?  actions?  discrete time?  continuous time?"  can the answer be true/false for each of these?  or are you asking perhaps about scaling (dimensionality, etc)? 
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 123 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs-Z1V9XZ4w7aW-wZZ:-MUtvo9j0Il6Cl2In4uh:bmakxvi) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L123)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

I changed a few things - the .py file wasn't animating for me. I needed to pass in the ax/show arguments to PyPlotVisualizer and left this in.
</blockquote></details>

would be better to fix the .py file?
___
*[exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb, line 463 at r1](https://reviewable.io/reviews/russtedrake/underactuated/418#-MUs0G7t5YGiEWlD1R1Z:-MUtw2V76vmNgbgGVSCd:b-4lvbj7) ([raw file](https://github.com/russtedrake/underactuated/blob/791d6af955c66d6705e44894167ba3f56d75d634/exercises/dp/fitted_double_integrator/fitted_double_integrator.ipynb#L463)):*
<details><summary><i>Previously, echen9898 (Eric Chen) wrote…</i></summary><blockquote>

Yeah I was debating this - I liked the mesh in terms of just exposing them to another drake system they can look up to get used to the docs. Using the nn directly is cleaner/more efficient and we could axe this
</blockquote></details>

i do think using the net is better.

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/418#-:-MUx1vd69SaS--rAik_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @echen9898)

**Pull request merged**
