### PR TITLE
Use URLs for model paths

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://github.com/RobotLocomotion/drake/pull/18157.
For packaged models, Drake recommends using URLs (not FindResource).

Not ported: `exercises`.
Not tested: `pip install underactuated`.

Hopefully you can carry this over the finish line, with whatever extra effort / testing you think it deserves?  I have my PR branch set to allow pushes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/509)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:eyes: looks good so far. I'll work on it.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/509#-:-NQ79zOsCHlbvRRXTg6G:b-1hqwoi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Hopefully you can carry this over the finish line, with whatever extra effort / testing you think it deserves?

For clarity -- my above was directed at @RussTedrake as the "you".  I think I've already done all we can as external contributors.

**Comment by jwnimmer-tri** [comment]
Also for the record -- there are a lot of ways to write the code for "How to prepare a Parser that knows about my project's models":
- an environment variable,
- a parser factory,
- a RobotDiagram factory,
- a package map singleton,
- etc.

I went with `ConfigureParser` here to make it extremely obvious (hopefully) to new users what was going on.  Simple control flow (no action at a distance), with a function that's imported from `underactuated`.

**Review by RussTedrake — APPROVED** [review]
Awesome.  Thank you!  I'm happy to accept this as is, and take it across the finish line in follow-up PRs.  

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/509#-:-NQ8N9Fw31zNOX-ODQci:b-fbf30j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
