### PR TITLE
Link edits in notebooks pset 2

### PR DESCRIPTION
**Pull request by iamsavva**
I'm sorry, the "8 commits ahead" bit is messy. Is that an issue? I can try to fix it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/535)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
we can squash on merge.

but remember that we want to PR to underactuated-solutions first... then the PR to underactuated should just be the installed files from that?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/535#-:-NqVPbzMAd4e2Aduri_d:btkgm0g)* status: all files reviewed, 1 unresolved discussion (waiting on @iamsavva)

___
*[`book/dp/exercises/minimum_time.ipynb` line 332 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/535#-NqVPQyK-oQMf6CeZiZ5:-NqVPQyK-oQMf6CeZiZ6:b77n5cz) ([raw file](https://github.com/RussTedrake/underactuated/blob/55b51cca8511a7741878d6acfe9eda36a12d3b74/book/dp/exercises/minimum_time.ipynb#L332)):*
> ```
>    "source": [
>     "## Animation of the Value-Iteration Algorithm\n",
>     "The animation of the value-iteration is coded mainly using matplotlib. If you are interested, feel free to check support function `create_animation` provided in [`minimum_time_utils.py`](https://github.com/RussTedrake/underactuated/blob/master/underactuated/exercises/dp/minimum_time_utils.py).\n",
> ```

i guess this is ok.  normally, for any methods that we recommend people reuse, they should be put in the underactuated module, and then documented so that they can be discovered here: https://underactuated.mit.edu/python/index.html .  Is it worth moving this?

**Comment by iamsavva** [comment]
Russ, according to the `underactuated-solutions` README 2021 Deepnote workflow (2024 seems to mirror that), we should:

1. edit `underactuated-solutions`
2. run `install.py`
3. push to `underactuated` master, wait till it's merged
4. push to `underactuated-solutions`

there is a small nit there too, because running `install.py` wants to make a bunch of small edits to formatting (I think somebody must have run `black .` on exercises underactuated-solutions but not underactuated).

So I was follow that; should we do things differently?


---

as for the link to `minimum_time_utils`. it's not in the sphinx docs you referenced; referencing the file itself doesn't work.

**Review by RussTedrake — COMMENTED** [review]
re: bunch of small edits.  i see this happen sometimes.  I just PR into solutions a copy of the pre-commit file from underactuated (which was slightly more up-to-date).  I think we need to figure out why they are acting differently sometime.

Re: minimum_time_utils.  I know.  I was asking whether we should move that method from it's current location into the underactuated module.  But I'm ok leaving it here.

> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/535#-:-Nq_BDp93hQblpk0pM7z:b-hps0to)* status: all files reviewed, 1 unresolved discussion (waiting on @iamsavva)

**Review by RussTedrake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iamsavva)

**Pull request merged**
