### PR TITLE
Drake pytorch

### PR DESCRIPTION
**Pull request by robert-verkuil**
This is a work in progress Pull Request adding NNSystem, a Drake Python Neural Network System powered by PyTorch.

Included is:
1) NNSystem
2) Example using NNSystem as a controller for a cartpole
3) Example using NNSystem as a Cost/Constraint in optimization
4) In Progress: Example using NNSystem with a simple Policy Gradient Algorithm

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/174)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
FTR Trying to get Reviewable to behave...

**Comment by EricCousineau-TRI** [comment]
Huh, seems like Reviewable won't permit assignments, but I guess it's b/c this repo isn't configured...

@RussTedrake Would you be OK if I set up Reviewable for this?

**Comment by EricCousineau-TRI** [comment]
___
*[src/drake_pytorch/assets/acrobot.sdf, line 1 at r2](https://reviewable.io/reviews/russtedrake/underactuated/174#-L_myv1F8g9wW7VHuYXg:-LaosXtfC9PeApzQyetr:buk8sfo) ([raw file](https://github.com/russtedrake/underactuated/blob/5db3225d32ad3a95228c28b36b3560222e55c7df/src/drake_pytorch/assets/acrobot.sdf#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Sorry, looking into this now!)
</blockquote></details>

Filed https://github.com/RobotLocomotion/drake/issues/11009
Will work on the acute solution; will clean up later.

**Comment by robert-verkuil** [comment]
saw that some circleCI tests were failing, so rebased onto the latest version of underactuated in hopes that that will improve things

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/russtedrake/underactuated/174#-Lb00fK_D7Tq7UkNE7cg:-Lb00fK_D7Tq7UkNE7ch:b-d79m0m) (no related file):*
Looks like CI wants `seaborn`?
https://circleci.com/gh/RussTedrake/underactuated/1082
```
36: ImportError: No module named seaborn
```

---

**Comment by RussTedrake** [comment]
sorry this hasn't landed.  am going to close it for now, but we've discussed it's existence often and certainly won't forget about it!

**Pull request closed without merging**
