### PR TITLE
Fix colab provisioning

### PR DESCRIPTION
**Pull request by gizatt**
WIP. @EricCousineau-TRI @RussTedrake please LMK (if CI doesn't) if the particular versioning of these libraries was important -- this change puts them in line with what colab wants them to be.

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/223)

### CODE REVIEW

**Comment by gizatt** [comment]
This seems to *almost* install properly on colab, but `python3-u-msgpack` is apt-installed by Drake, and then `meshcat` depends on it as well, causing pip to throw an error that it can't uninstall the apt-installed version to install whatever other version it wants to grab.

But changing tornado versions breaks jupyter notebooks on CI, looks like...

**Comment by EricCousineau-TRI** [comment]
Hm... Is it that doing negative tests for versions is less conservative than using bounds?

Perhaps the requirement specifiers allow both `~=` and `<` to be used?
https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

**Comment by RussTedrake** [comment]
@gizatt -- sorry I lost track of this one.  is it now obsolete?

**Comment by gizatt** [comment]
Probably? At least, an independent modern look at what requirements should be used is probably warranted.

**Pull request closed without merging**
