### PR TITLE
Added lambda constraint to sos_roa2() in lyapunov.ipynb for conformance with S-Procedure

### PR DESCRIPTION
**Pull request by virgil382**
For "S-Procedure" conformance, lambda_ should be positive.

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/481)

### CODE REVIEW

**Comment by virgil382** [comment]
With the constraint added, the resulting rho is 0.9999999802199994, which is less sexy than 1.0.  But since this is a teaching tool, it is clearer to specify the constraint so that the theory and the practice are more closely aligned.

**Comment by RussTedrake** [comment]
Awesome that you wrote up a pull request.  Thanks!

But the code is correct as is.  In the second formulation of regions of attraction, it is sufficient to say Vdot == 0 => V >= rho.  (the more careful code in C++ also ensures that Vdot is locally negative definite at the origin).  When the S-procedure is implementing an equality constraint, then we do not require that lambda is SOS (or positive, in the scalar case).

**Comment by virgil382** [comment]
Thank you for the explanation.  I'm still trying to wrap my mind around
this second formulation (with an unconstrained lambda).  It usually clicks
a few days later :)
Best regards,
--Virgil

**Comment by virgil382** [comment]
I'm convinced after reading III.B. in "Sampling Quotient-Ring
Sum-of-Squares Programs for Scalable Verification of Nonlinear Systems".
Very nice explanation.

For what it's worth, here are my notes outlining a very informal
(classroom style and hands waving in the air) type of proof.  I'm not sure
if it convinces anyone else, but it does me. :)

Thank you kindly again.

[image: image.png]

**Comment by RussTedrake** [comment]
I'm happy to take a look -- but the image didn't seem to get attached correctly?

**Pull request closed without merging**
