### PR TITLE
Added perching glider exercise

### PR DESCRIPTION
**Pull request by echen9898**
* Added an exercise section to chapter 18

* Added perching glider sysid notebook

* Added perching glider tests

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/441)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/441)* status: all files reviewed, 6 unresolved discussions (waiting on @echen9898)

___
*[sysid.html, line 878 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSvfPy9HTgmUevtisJ:-MZSvfPz2getGa8eglc8:b-s2ht3b) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/sysid.html#L878)):*
> ```HTML
>     <exercise id="glider_sysid"><h1>System Identification for the Perching Glider</h1>
> 
>       <p>In this exercise we will use physically inspired basis functions to fit the nonlinear dynamics of a perching glider.  <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/sysid/glider_sysid/glider_sysid.ipynb" target="_blank">In this python notebook</a>, you will need to implement least-squares fitting and find the best set of basis functions that describe the dynamics of the glider.  Take the time to go through the notebook and understand the code in it, and then answer the following questions.  The written questions will also be listed in the notebook for your convenience.</p>
> ```

nit: physically-inspired
___
*[sysid.html, line 878 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSvmIi7Hxh1Ve8Um1C:-MZSvmIi7Hxh1Ve8Um1D:b-k5fmty) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/sysid.html#L878)):*
> ```HTML
>     <exercise id="glider_sysid"><h1>System Identification for the Perching Glider</h1>
> 
>       <p>In this exercise we will use physically inspired basis functions to fit the nonlinear dynamics of a perching glider.  <a href="https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/exercises/sysid/glider_sysid/glider_sysid.ipynb" target="_blank">In this python notebook</a>, you will need to implement least-squares fitting and find the best set of basis functions that describe the dynamics of the glider.  Take the time to go through the notebook and understand the code in it, and then answer the following questions.  The written questions will also be listed in the notebook for your convenience.</p>
> ```

nit: there's just one question
___
*[sysid.html, line 884 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSvtCW1Ie84suuoml0:-MZSvtCW1Ie84suuoml1:b-hog8np) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/sysid.html#L884)):*
> ```HTML
>         <li>Work through the coding sections in the notebook.</li>
> 
>         <li>All of the basis configurations we tested used at most 3 basis functions to compute a single acceleration. If we increase the number of basis functions used to compute a single acceleration to 4, the least-squares residual goes down. Why would we limit ourselves to 3 basis functions if by using more we can generate a better fit?</li>
> ```

fwiw, this is pretty open-ended.  doesn't have a precise answer.
___
*[exercises/sysid/glider_sysid/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSw-U46szjQBLfHzgp:-MZSw-U46szjQBLfHzgq:bh1nkwz) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/exercises/sysid/glider_sysid/BUILD.bazel#L11)):*
> ```Starlark
> rt_ipynb_test(
>     name = "glider_sysid",
>     timeout = "moderate",
> ```

that's a red flag.  can we add in "running_as_notebook" to help?
___
*[exercises/sysid/glider_sysid/glider_sysid.ipynb, line 217 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSwD1L97DrOyEbY4Op:-MZSwD1L97DrOyEbY4Oq:ba4lnc4) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/exercises/sysid/glider_sysid/glider_sysid.ipynb#L217)):*
> ```
>     "# Global simulation parameters\n",
>     "dt = 0.01 # timestep duration\n",
>     "N = 50 # number of timesteps\n",
> ```

for instance, you can set this to be super small if running_as_notebook is False
___
*[exercises/sysid/glider_sysid/glider_sysid.ipynb, line 225 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSwIBZ83yOPJcMcanG:-MZSwIBZ83yOPJcMcanH:b-wgfcas) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/exercises/sysid/glider_sysid/glider_sysid.ipynb#L225)):*
> ```
>     "trajectories = dict()\n",
>     "times = [t*dt for t in range(N+1)]\n",
>     "for traj in range(15):\n",
> ```

this could also be a small number if running_as_notebook if False

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/441)* status: all files reviewed, 5 unresolved discussions (waiting on @echen9898)

**Review by echen9898 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/441)* status: all files reviewed, 3 unresolved discussions (waiting on @RussTedrake)

___
*[sysid.html, line 884 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSvtCW1Ie84suuoml0:-MZTA7PV74bF_iWG35vr:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/sysid.html#L884)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

fwiw, this is pretty open-ended.  doesn't have a precise answer.
</blockquote></details>

Done.
___
*[exercises/sysid/glider_sysid/glider_sysid.ipynb, line 217 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSwD1L97DrOyEbY4Op:-MZTAE9fAA-oP0lDPZst:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/exercises/sysid/glider_sysid/glider_sysid.ipynb#L217)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

for instance, you can set this to be super small if running_as_notebook is False
</blockquote></details>

Done.
___
*[exercises/sysid/glider_sysid/glider_sysid.ipynb, line 225 at r1](https://reviewable.io/reviews/russtedrake/underactuated/441#-MZSwIBZ83yOPJcMcanG:-MZTAF7t39x9HBE47Go2:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/67f6136e21a56eb11b3253c12aced39567825298/exercises/sysid/glider_sysid/glider_sysid.ipynb#L225)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this could also be a small number if running_as_notebook if False
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/441)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @echen9898)

**Pull request merged**
