### PR TITLE
Add GCS footstep planning empty notebook and Autograder

### PR DESCRIPTION
**Pull request by Tangsun**
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519)

### CODE REVIEW

**Comment by TobiaMarcucci** [comment]
Hi all! The code looks great to me overall and I could run it fine with the notebook that Sunbochen sent me (which seems to be the same as the one here, but with the solutions plugged in).

I've seen that you are using SNOPT to solve the convex relaxation. However, in the notebook that Sunbochen sent me, when I ran the function `generate_and_animate_footstep_plan` in the last cell it was still trying to use MOSEK somewhere in `G.SolveShortestPath`. I had to add the directory of my MOSEK license to the env as `MOSEKLM_LICENSE_FILE` to make it work. Maybe this is something that you want to look into?

Also, as a high-level comment, maybe one could consider moving some of the less important functions in a separate python file. For example the code that produces the animations, or having some methods that allow copying the regions multiple times without having a for loop, etc. Since I think that they could make the notebook shorter and easier to navigate for the non experts. Also for the student I think it's more exciting if the ratio between the code they write looks larger than the one they have to understand?

Said this, it looks very nice overall!

Please let me know if you want me to comment on something specific.

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Tangsun)

___
*[`exercises/humanoids/footstep_planning_gcs.ipynb` line 730 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUDRAjW5PR5ff-X65yS:-NUDRAjW5PR5ff-X65yT:b-vanrvb) ([raw file](https://github.com/RussTedrake/underactuated/blob/d2d88014a970a4104e8b6e92f9de9cc7d4db718d/exercises/humanoids/footstep_planning_gcs.ipynb#L730)):*
> ```
>     "convex_relaxation = True\n",
>     "\n",
>     "solver = SnoptSolver()\n",
> ```

I thought we were going with ClpSolver?

**Review by RussTedrake — CHANGES_REQUESTED** [review]
I'm not sure 

> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519#-:-NUDTIP70hMKQ4uVl1r6:b-mnewzc)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Tangsun)

___
*[`underactuated/exercises/humanoids/test_footstep_planning_gcs.py` line 24 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUDTtif1kyQ0LlTtnVQ:-NUDTtif1kyQ0LlTtnVR:blxjq07) ([raw file](https://github.com/RussTedrake/underactuated/blob/d2d88014a970a4104e8b6e92f9de9cc7d4db718d/underactuated/exercises/humanoids/test_footstep_planning_gcs.py#L24)):*
> ```Python
>         Terrain = self.notebook_locals["Terrain"]
>         self.footstep_planner = self.notebook_locals["GCS_footstep_planner"]
>         self.solver = self.notebook_locals["solver"]
> ```

presumably this was not getting set correctly when Tobia ran it?  why not just hard-code the SnoptSolver (or ClpSolver) here , too?

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Tangsun)

___
*[`exercises/humanoids/footstep_planning_gcs.ipynb` line 599 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUDmr_k9m1kLjuTaUAG:-NUDmr_k9m1kLjuTaUAH:b-es4y17) ([raw file](https://github.com/RussTedrake/underactuated/blob/d2d88014a970a4104e8b6e92f9de9cc7d4db718d/exercises/humanoids/footstep_planning_gcs.ipynb#L599)):*
> ```
>     "    options.max_rounded_paths = 10\n",
>     "    options.convex_relaxation = convex_relaxation\n",
>     "    options.solver = solver\n",
> ```

let's fix the random seed used in the rounding to make sure we have deterministic results:
https://drake.mit.edu/doxygen_cxx/structdrake_1_1geometry_1_1optimization_1_1_graph_of_convex_sets_options.html#abb7b16d4d092f7b7572de4c058b30d96

**Comment by RussTedrake** [comment]
*[`exercises/humanoids/footstep_planning_gcs.ipynb` line 599 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUDmr_k9m1kLjuTaUAG:-NUDnKRv8PPaoD3wVwgh:b-aelmma) ([raw file](https://github.com/RussTedrake/underactuated/blob/d2d88014a970a4104e8b6e92f9de9cc7d4db718d/exercises/humanoids/footstep_planning_gcs.ipynb#L599)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

let's fix the random seed used in the rounding to make sure we have deterministic results:
https://drake.mit.edu/doxygen_cxx/structdrake_1_1geometry_1_1optimization_1_1_graph_of_convex_sets_options.html#abb7b16d4d092f7b7572de4c058b30d96
</blockquote></details>

withdrawn.  actually, i guess it's fixed to zero if we haven't picked anything else.  so we should get deterministic results.

**Review by Tangsun — COMMENTED** [review]
I think the notebook Tobia ran was an older version which incorrectly has Mosek hardcoded as the solver choice. The latest one in this repo has fixed this issue by adding solver as an argument to the GCS_footstep_planner function. Currently the notebook runs with SnoptSolver.

In addition, it seems like the seed is chosen by default. This is consistent with numerical results. The solutions for both Terrains were generated (with Snopt being the solver) multiple times and the results are always the same.

**Comment by Tangsun** [comment]
Thank you both for your suggestions! I have incorporated the changes: (1) fixing Snopt as the solver for autograder test (2) I moved two matplotlib-related functions for rectangle plots and  to a separate python file "footstep_planning_gcs_utils.py"

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519)* status: all files reviewed, 2 unresolved discussions (waiting on @Tangsun)

___
*[`exercises/humanoids/footstep_planning_gcs.ipynb` line 35 at r3](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUE22rBAJ7qD6cN2pWz:-NUE22rBAJ7qD6cN2pX-:b-tq91c8) ([raw file](https://github.com/RussTedrake/underactuated/blob/4e413b279e09d9aa844c403d959254a4bb0e9943/exercises/humanoids/footstep_planning_gcs.ipynb#L35)):*
> ```
>     "\n",
>     "# import helper functions\n",
>     "from footstep_planning_gcs_utils import plot_rectangle, animate_footstep_plan"
> ```

i think we had trouble making this work before. 

and i can now tell that you didn't add it to the Bazel.build and you're not running the tests.
___
*[`exercises/humanoids/footstep_planning_gcs.ipynb` line 333 at r3](https://reviewable.io/reviews/RussTedrake/underactuated/519#-NUE1npx9_73xVixLX1S:-NUE1npx9_73xVixLX1T:b-3lcsn0) ([raw file](https://github.com/RussTedrake/underactuated/blob/4e413b279e09d9aa844c403d959254a4bb0e9943/exercises/humanoids/footstep_planning_gcs.ipynb#L333)):*
> ```
>     {
>      "data": {
>       "image/png": "iVBORw0KGgoAAAANSUhEUgAAA0YAAAEoCAYAAAB8ReEbAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAgNklEQVR4nO3df1DUdeLH8Rc/YpFLMG8F/LEMVl7iqKCQDP24q5PEH+PlTNdYWhpjNpV46nZ3SVeQ57fwLjU6oyjL824uRu6605r0cDw8crq4UIiZatCyHwejLbjjxCJcoCzfP5q22xEJjA8f3PfzMfP5Y9/7fu++aD85+5rP7nvDenp6egQAAAAABgu3OwAAAAAA2I1iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONF2h1gsPn9fp08eVIjR45UWFiY3XEAAAAA2KSnp0dtbW0aN26cwsP7viYUcsXo5MmTcrlcdscAAAAAMEw0NTVpwoQJfc4JuWI0cuRISV/98bGxsTanAQAAAGAXn88nl8sV6Ah9Cbli9PXH52JjYylGAAAAAPr1FRs2XwAAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHiWFqNDhw5p4cKFGjdunMLCwrRnz55vXVNVVaWZM2fK4XDo6quv1s6dO62MCAAAAADWFqP29nalpqaqpKSkX/M//fRTLViwQDfffLPq6+u1du1a3Xvvvdq/f7+VMQEAAAAYztLtuufNm6d58+b1e35paakmTpyoLVu2SJJSUlL01ltv6emnn1ZOTo5VMQEAAAAYblj9jlF1dbWys7ODxnJycrR27doLruns7FRnZ2fgts/nsyreRWlsbJTX67U7BgAAADBknE6nkpKS7I4xIMOqGHk8HiUkJASNJSQkyOfz6b///a9GjBhx3pqioiJt2LBhqCIOSGNjo1JSUtTR0WF3FAAAAGDIxMTEqKGh4ZIqR8OqGF2M/Px8ud3uwG2fzyeXy2Vjom94vV51dHRo25+2aVLKJLvjAAAAAJb7qOEjrb5rtbxeL8XoYiUmJqq5uTlorLm5WbGxsb1eLZIkh8Mhh8MxFPEu2qSUSZo2c5rdMQAAAABcwLD6HaOsrCxVVlYGjR04cEBZWVk2JQIAAABgAkuL0ZkzZ1RfX6/6+npJX23HXV9fr8bGRklffQxu2bJlgfn333+/PvnkE/3yl7/U0aNH9dxzz+nPf/6z1q1bZ2VMAAAAAIaztBgdOXJEM2bM0IwZMyRJbrdbM2bMUEFBgSTp888/D5QkSZo4caL27t2rAwcOKDU1VVu2bNFLL73EVt0AAAAALGXpd4xuuukm9fT0XPD+nTt39rrm3XfftTAVAAAAAAQbVt8xAgAAAAA7UIwAAAAAGI9iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8ihEAAAAA41GMAAAAABiPYgQAAADAeBQjAAAAAMazvBiVlJQoOTlZ0dHRyszMVE1NTZ/zi4uLdc0112jEiBFyuVxat26dvvzyS6tjAgAAADCYpcWovLxcbrdbhYWFqqurU2pqqnJyctTS0tLr/LKyMq1fv16FhYVqaGjQyy+/rPLycj3yyCNWxgQAAABgOEuL0datW7Vy5Url5uZqypQpKi0tVUxMjHbs2NHr/LffflvXX3+9lixZouTkZM2ZM0d33nnnt15lAgAAAIDvwrJi1NXVpdraWmVnZ3/zZOHhys7OVnV1da9rrrvuOtXW1gaK0CeffKJ9+/Zp/vz5F3yezs5O+Xy+oAMAAAAABiLSqgf2er3q7u5WQkJC0HhCQoKOHj3a65olS5bI6/XqhhtuUE9Pj86dO6f777+/z4/SFRUVacOGDYOaHQAAAIBZhtWudFVVVXryySf13HPPqa6uTn/729+0d+9ebdy48YJr8vPz1draGjiampqGMDEAAACAUGDZFSOn06mIiAg1NzcHjTc3NysxMbHXNY899pjuvvtu3XvvvZKkadOmqb29Xffdd59+9atfKTz8/B7ncDjkcDgG/w8AAAAAYAzLrhhFRUUpPT1dlZWVgTG/36/KykplZWX1uqajo+O88hMRESFJ6unpsSoqAAAAAMNZdsVIktxut5YvX66MjAzNmjVLxcXFam9vV25uriRp2bJlGj9+vIqKiiRJCxcu1NatWzVjxgxlZmbq+PHjeuyxx7Rw4cJAQQIAAACAwWZpMVq8eLFOnTqlgoICeTwepaWlqaKiIrAhQ2NjY9AVokcffVRhYWF69NFHdeLECY0ZM0YLFy7UE088YWVMAAAAAIaztBhJUl5envLy8nq9r6qqKjhMZKQKCwtVWFhodSwAAAAACBhWu9IBAAAAgB0oRgAAAACMRzECAAAAYDyKEQAAAADjUYwAAAAAGI9iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8y4tRSUmJkpOTFR0drczMTNXU1PQ5/4svvtCqVas0duxYORwO/eAHP9C+ffusjgkAAADAYJFWPnh5ebncbrdKS0uVmZmp4uJi5eTk6NixY4qPjz9vfldXl2655RbFx8fr1Vdf1fjx4/Wf//xHo0aNsjImAAAAAMNZWoy2bt2qlStXKjc3V5JUWlqqvXv3aseOHVq/fv1583fs2KHTp0/r7bff1mWXXSZJSk5OtjIiAAAAAFhXjLq6ulRbW6v8/PzAWHh4uLKzs1VdXd3rmtdff11ZWVlatWqVXnvtNY0ZM0ZLlizRww8/rIiIiF7XdHZ2qrOzM3Db5/MN7h8yCD5q+MjuCAAAAMCQuFTf+1pWjLxer7q7u5WQkBA0npCQoKNHj/a65pNPPtHBgwe1dOlS7du3T8ePH9eDDz6os2fPqrCwsNc1RUVF2rBhw6DnHwxOp1MxMTFafddqu6MAAAAAQyYmJkZOp9PuGANi6UfpBsrv9ys+Pl4vvviiIiIilJ6erhMnTuipp566YDHKz8+X2+0O3Pb5fHK5XEMVuU9JSUlqaGiQ1+u1OwoAAAAwZJxOp5KSkuyOMSCWFSOn06mIiAg1NzcHjTc3NysxMbHXNWPHjtVll10W9LG5lJQUeTwedXV1KSoq6rw1DodDDodjcMMPoqSkpEvupAAAAABMY9l23VFRUUpPT1dlZWVgzO/3q7KyUllZWb2uuf7663X8+HH5/f7A2IcffqixY8f2WooAAAAAYDBY+jtGbrdb27dv1x/+8Ac1NDTogQceUHt7e2CXumXLlgVtzvDAAw/o9OnTWrNmjT788EPt3btXTz75pFatWmVlTAAAAACGs/Q7RosXL9apU6dUUFAgj8ejtLQ0VVRUBDZkaGxsVHj4N93M5XJp//79WrdunaZPn67x48drzZo1evjhh62MCQAAAMBwYT09PT12hxhMPp9PcXFxam1tVWxsrN1xAAAAANhkIN3A0o/SAQAAAMClgGIEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8ihEAAAAA40XaHSDUNTY2yuv12h0DIc7pdCopKcnuGACASwTvT2C1S/G9CcXIQo2NjUpJSVFHR4fdURDiYmJi1NDQcMn9AwQAGHq8P8FQuBTfm1CMLOT1etXR0aFtf9qmSSmT7I6DEPVRw0dafddqeb3eS+ofHwCAPXh/Aqtdqu9NKEZDYFLKJE2bOc3uGAAAAAG8PwGCsfkCAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGC8ISlGJSUlSk5OVnR0tDIzM1VTU9Ovdbt27VJYWJgWLVpkbUAAAAAARrO8GJWXl8vtdquwsFB1dXVKTU1VTk6OWlpa+lz32Wef6ec//7luvPFGqyMCAAAAMJzlxWjr1q1auXKlcnNzNWXKFJWWliomJkY7duy44Jru7m4tXbpUGzZs0JVXXml1RAAAAACGs7QYdXV1qba2VtnZ2d88YXi4srOzVV1dfcF1v/71rxUfH68VK1Z863N0dnbK5/MFHQAAAAAwEJYWI6/Xq+7ubiUkJASNJyQkyOPx9Lrmrbfe0ssvv6zt27f36zmKiooUFxcXOFwu13fODQAAAMAsw2pXura2Nt19993avn27nE5nv9bk5+ertbU1cDQ1NVmcEgAAAECoibTywZ1OpyIiItTc3Bw03tzcrMTExPPmf/zxx/rss8+0cOHCwJjf7/8qaGSkjh07pquuuipojcPhkMPhsCA9AAAAAFNYesUoKipK6enpqqysDIz5/X5VVlYqKyvrvPmTJ0/We++9p/r6+sDxk5/8RDfffLPq6+v5mBwAAAAAS1h6xUiS3G63li9froyMDM2aNUvFxcVqb29Xbm6uJGnZsmUaP368ioqKFB0dralTpwatHzVqlCSdNw4AAAAAg8XyYrR48WKdOnVKBQUF8ng8SktLU0VFRWBDhsbGRoWHD6uvOgEAAAAwjOXFSJLy8vKUl5fX631VVVV9rt25c+fgBwIAAACA/8GlGgAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8ihEAAAAA41GMAAAAABiPYgQAAADAeBQjAAAAAMajGAEAAAAwHsUIAAAAgPEoRgAAAACMRzECAAAAYDyKEQAAAADjUYwAAAAAGI9iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIw3JMWopKREycnJio6OVmZmpmpqai44d/v27brxxht1xRVX6IorrlB2dnaf8wEAAADgu7K8GJWXl8vtdquwsFB1dXVKTU1VTk6OWlpaep1fVVWlO++8U//85z9VXV0tl8ulOXPm6MSJE1ZHBQAAAGAoy4vR1q1btXLlSuXm5mrKlCkqLS1VTEyMduzY0ev8V155RQ8++KDS0tI0efJkvfTSS/L7/aqsrLQ6KgAAAABDWVqMurq6VFtbq+zs7G+eMDxc2dnZqq6u7tdjdHR06OzZsxo9enSv93d2dsrn8wUdAAAAADAQlhYjr9er7u5uJSQkBI0nJCTI4/H06zEefvhhjRs3Lqhc/a+ioiLFxcUFDpfL9Z1zAwAAADDLsN6VbtOmTdq1a5d2796t6OjoXufk5+ertbU1cDQ1NQ1xSgAAAACXukgrH9zpdCoiIkLNzc1B483NzUpMTOxz7ebNm7Vp0yb94x//0PTp0y84z+FwyOFwDEpeAAAAAGay9IpRVFSU0tPTgzZO+HojhaysrAuu++1vf6uNGzeqoqJCGRkZVkYEAAAAAGuvGEmS2+3W8uXLlZGRoVmzZqm4uFjt7e3Kzc2VJC1btkzjx49XUVGRJOk3v/mNCgoKVFZWpuTk5MB3kS6//HJdfvnlVscFAAAAYCDLi9HixYt16tQpFRQUyOPxKC0tTRUVFYENGRobGxUe/s2Fq+eff15dXV366U9/GvQ4hYWFevzxx62OCwAAAMBAlhcjScrLy1NeXl6v91VVVQXd/uyzz6wPBAAAAAD/Y1jvSgcAAAAAQ4FiBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8ihEAAAAA41GMAAAAABiPYgQAAADAeBQjAAAAAMYbkmJUUlKi5ORkRUdHKzMzUzU1NX3O/8tf/qLJkycrOjpa06ZN0759+4YiJgAAAABDWV6MysvL5Xa7VVhYqLq6OqWmpionJ0ctLS29zn/77bd15513asWKFXr33Xe1aNEiLVq0SO+//77VUQEAAAAYyvJitHXrVq1cuVK5ubmaMmWKSktLFRMTox07dvQ6/5lnntHcuXP1i1/8QikpKdq4caNmzpypZ5991uqoAAAAAAwVaeWDd3V1qba2Vvn5+YGx8PBwZWdnq7q6utc11dXVcrvdQWM5OTnas2dPr/M7OzvV2dkZuO3z+b57cAD90tjYKK/Xa8tzO51OJSUl2fLcJrLrtbbzdeb8NoeJ5zeA81lajLxer7q7u5WQkBA0npCQoKNHj/a6xuPx9Drf4/H0Or+oqEgbNmwYnMAA+q2xsVEpKSnq6Oiw5fljYmLU0NDAm4ohYOdrbdfrzPltDhPPbwC9s7QYDYX8/PygK0w+n08ul8vGRIAZvF6vOjo6tO1P2zQpZdKQPvdHDR9p9V2r5fV6eUMxBOx6re18nTm/zWHi+Q2gd5YWI6fTqYiICDU3NweNNzc3KzExsdc1iYmJA5rvcDjkcDgGJzCAAZuUMknTZk6zOwaGgImvtYl/s6l4rQFYuvlCVFSU0tPTVVlZGRjz+/2qrKxUVlZWr2uysrKC5kvSgQMHLjgfAAAAAL4ryz9K53a7tXz5cmVkZGjWrFkqLi5We3u7cnNzJUnLli3T+PHjVVRUJElas2aNfvSjH2nLli1asGCBdu3apSNHjujFF1+0OioAAAAAQ1lejBYvXqxTp06poKBAHo9HaWlpqqioCGyw0NjYqPDwby5cXXfddSorK9Ojjz6qRx55RJMmTdKePXs0depUq6MCAAAAMNSQbL6Ql5envLy8Xu+rqqo6b+z222/X7bffbnEqAAAAAPiK5T/wCgAAAADDHcUIAAAAgPEoRgAAAACMRzECAAAAYDyKEQAAAADjUYwAAAAAGI9iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8y4rR6dOntXTpUsXGxmrUqFFasWKFzpw50+f81atX65prrtGIESOUlJSkn/3sZ2ptbbUqIgAAAABIsrAYLV26VB988IEOHDigN954Q4cOHdJ99913wfknT57UyZMntXnzZr3//vvauXOnKioqtGLFCqsiAgAAAIAkKdKKB21oaFBFRYUOHz6sjIwMSdK2bds0f/58bd68WePGjTtvzdSpU/XXv/41cPuqq67SE088obvuukvnzp1TZKQlUQEAAADAmitG1dXVGjVqVKAUSVJ2drbCw8P1zjvv9PtxWltbFRsb22cp6uzslM/nCzoAAAAAYCAsKUYej0fx8fFBY5GRkRo9erQ8Hk+/HsPr9Wrjxo19fvxOkoqKihQXFxc4XC7XRecGAAAAYKYBFaP169crLCysz+Po0aPfOZTP59OCBQs0ZcoUPf74433Ozc/PV2tra+Boamr6zs8PAAAAwCwD+uLOQw89pHvuuafPOVdeeaUSExPV0tISNH7u3DmdPn1aiYmJfa5va2vT3LlzNXLkSO3evVuXXXZZn/MdDoccDke/8gMAAABAbwZUjMaMGaMxY8Z867ysrCx98cUXqq2tVXp6uiTp4MGD8vv9yszMvOA6n8+nnJwcORwOvf7664qOjh5IPAAAAAC4KJZ8xyglJUVz587VypUrVVNTo3/961/Ky8vTHXfcEdiR7sSJE5o8ebJqamokfVWK5syZo/b2dr388svy+XzyeDzyeDzq7u62IiYAAAAASLJou25JeuWVV5SXl6fZs2crPDxct912m373u98F7j979qyOHTumjo4OSVJdXV1gx7qrr7466LE+/fRTJScnWxUVAAAAgOEsK0ajR49WWVnZBe9PTk5WT09P4PZNN90UdBsAAAAAhoolH6UDAAAAgEsJxQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYj2IEAAAAwHgUIwAAAADGoxgBAAAAMB7FCAAAAIDxKEYAAAAAjEcxAgAAAGA8ihEAAAAA41GMAAAAABiPYgQAAADAeBQjAAAAAMajGAEAAAAwHsUIAAAAgPEoRgAAAACMZ1kxOn36tJYuXarY2FiNGjVKK1as0JkzZ/q1tqenR/PmzVNYWJj27NljVUQAAAAAkGRhMVq6dKk++OADHThwQG+88YYOHTqk++67r19ri4uLFRYWZlU0AAAAAAgSacWDNjQ0qKKiQocPH1ZGRoYkadu2bZo/f742b96scePGXXBtfX29tmzZoiNHjmjs2LFWxAMAAACAIJZcMaqurtaoUaMCpUiSsrOzFR4ernfeeeeC6zo6OrRkyRKVlJQoMTGxX8/V2dkpn88XdAAAAADAQFhSjDwej+Lj44PGIiMjNXr0aHk8nguuW7duna677jrdeuut/X6uoqIixcXFBQ6Xy3XRuQEAAACYaUDFaP369QoLC+vzOHr06EUFef3113Xw4EEVFxcPaF1+fr5aW1sDR1NT00U9PwAAAABzDeg7Rg899JDuueeePudceeWVSkxMVEtLS9D4uXPndPr06Qt+RO7gwYP6+OOPNWrUqKDx2267TTfeeKOqqqp6XedwOORwOPr7JwAAAADAeQZUjMaMGaMxY8Z867ysrCx98cUXqq2tVXp6uqSvio/f71dmZmava9avX6977703aGzatGl6+umntXDhwoHEBAAAAIABsWRXupSUFM2dO1crV65UaWmpzp49q7y8PN1xxx2BHelOnDih2bNn649//KNmzZqlxMTEXq8mJSUlaeLEiVbEBAAAAABJFv6O0SuvvKLJkydr9uzZmj9/vm644Qa9+OKLgfvPnj2rY8eOqaOjw6oIAAAAANAvllwxkqTRo0errKzsgvcnJyerp6enz8f4tvsBAAAAYDBYdsUIAAAAAC4VFCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgPIoRAAAAAONRjAAAAAAYz7IfeMU3Pmr4yO4ICGF2n192PL/df7Ophvq/+3B4nTm/zcH5DQyeS/XcohhZyOl0KiYmRqvvWm13FIS4mJgYOZ3OIX1Ou89vO/5mU9n5Wtv1OnN+m4PzG7DGpfjvWFhPT0+P3SEGk8/nU1xcnFpbWxUbG2t3HDU2Nsrr9dodAyHO6XQqKSlpyJ/XzvPbrr/ZVHa91na+zpzf5uD8BgbfcPl3bCDdgGIEAAAAICQNpBuw+QIAAAAA41GMAAAAABiPYgQAAADAeBQjAAAAAMajGAEAAAAwHsUIAAAAgPEoRgAAAACMF2l3gMH29c8y+Xw+m5MAAAAAsNPXnaA/P90acsWora1NkuRyuWxOAgAAAGA4aGtrU1xcXJ9zwnr6U58uIX6/XydPntTIkSMVFhZmdxwMkM/nk8vlUlNT07f+OjFwMTjHYDXOMQwFzjNYLVTOsZ6eHrW1tWncuHEKD+/7W0Qhd8UoPDxcEyZMsDsGvqPY2NhL+n9CDH+cY7Aa5xiGAucZrBYK59i3XSn6GpsvAAAAADAexQgAAACA8ShGGFYcDocKCwvlcDjsjoIQxTkGq3GOYShwnsFqJp5jIbf5AgAAAAAMFFeMAAAAABiPYgQAAADAeBQjAAAAAMajGAEAAAAwHsUIw0pJSYmSk5MVHR2tzMxM1dTU2B0JIeLQoUNauHChxo0bp7CwMO3Zs8fuSAgxRUVFuvbaazVy5EjFx8dr0aJFOnbsmN2xEEKef/55TZ8+PfCDm1lZWfr73/9udyyEsE2bNiksLExr1661O8qQoBhh2CgvL5fb7VZhYaHq6uqUmpqqnJwctbS02B0NIaC9vV2pqakqKSmxOwpC1JtvvqlVq1bp3//+tw4cOKCzZ89qzpw5am9vtzsaQsSECRO0adMm1dbW6siRI/rxj3+sW2+9VR988IHd0RCCDh8+rBdeeEHTp0+3O8qQYbtuDBuZmZm69tpr9eyzz0qS/H6/XC6XVq9erfXr19ucDqEkLCxMu3fv1qJFi+yOghB26tQpxcfH680339QPf/hDu+MgRI0ePVpPPfWUVqxYYXcUhJAzZ85o5syZeu655/R///d/SktLU3Fxsd2xLMcVIwwLXV1dqq2tVXZ2dmAsPDxc2dnZqq6utjEZAFyc1tZWSV+9cQUGW3d3t3bt2qX29nZlZWXZHQchZtWqVVqwYEHQ+zITRNodAJAkr9er7u5uJSQkBI0nJCTo6NGjNqUCgIvj9/u1du1aXX/99Zo6dardcRBC3nvvPWVlZenLL7/U5Zdfrt27d2vKlCl2x0II2bVrl+rq6nT48GG7oww5ihEAAINs1apVev/99/XWW2/ZHQUh5pprrlF9fb1aW1v16quvavny5XrzzTcpRxgUTU1NWrNmjQ4cOKDo6Gi74ww5ihGGBafTqYiICDU3NweNNzc3KzEx0aZUADBweXl5euONN3To0CFNmDDB7jgIMVFRUbr66qslSenp6Tp8+LCeeeYZvfDCCzYnQyiora1VS0uLZs6cGRjr7u7WoUOH9Oyzz6qzs1MRERE2JrQW3zHCsBAVFaX09HRVVlYGxvx+vyorK/nsNIBLQk9Pj/Ly8rR7924dPHhQEydOtDsSDOD3+9XZ2Wl3DISI2bNn67333lN9fX3gyMjI0NKlS1VfXx/SpUjiihGGEbfbreXLlysjI0OzZs1ScXGx2tvblZuba3c0hIAzZ87o+PHjgduffvqp6uvrNXr0aCUlJdmYDKFi1apVKisr02uvvaaRI0fK4/FIkuLi4jRixAib0yEU5Ofna968eUpKSlJbW5vKyspUVVWl/fv32x0NIWLkyJHnfS/ye9/7nr7//e8b8X1JihGGjcWLF+vUqVMqKCiQx+NRWlqaKioqztuQAbgYR44c0c033xy47Xa7JUnLly/Xzp07bUqFUPL8889Lkm666aag8d///ve65557hj4QQk5LS4uWLVumzz//XHFxcZo+fbr279+vW265xe5oQEjgd4wAAAAAGI/vGAEAAAAwHsUIAAAAgPEoRgAAAACMRzECAAAAYDyKEQAAAADjUYwAAAAAGI9iBAAAAMB4FCMAAAAAxqMYAQAAADAexQgAAACA8ShGAAAAAIxHMQIAAABgvP8HExgbNCeqSt4AAAAASUVORK5CYII=",
> ```

this won't pass CI.  you have output in the notebook.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tangsun)

**Pull request merged**
