### PR TITLE
Ilqr test fix

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486)

### CODE REVIEW

**Review by lujieyang — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486#-:-My8tXCh7xtGe6SzvF15:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[exercises/trajopt/orbital_transfer/orbital_transfer.ipynb, line 810 at r3](https://reviewable.io/reviews/russtedrake/underactuated/486#-My8ybfODe3AHPEDF49_:-My8ybfODe3AHPEDF49a:bq0ermm) ([raw file](https://github.com/russtedrake/underactuated/blob/d2b9b7bc1b170ef2941b4f84524a8eb4c6b87604/exercises/trajopt/orbital_transfer/orbital_transfer.ipynb#L810)):*
> ```
>    "nbconvert_exporter": "python",
>    "pygments_lexer": "ipython3",
>    "version": "3.8.10"
> ```

would be nice not to have these, but meh...
___
*[underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py, line 248 at r3](https://reviewable.io/reviews/russtedrake/underactuated/486#-My8yVDTAzyPe9YfVz0O:-My8yVDTAzyPe9YfVz0P:b432qjd) ([raw file](https://github.com/russtedrake/underactuated/blob/d2b9b7bc1b170ef2941b4f84524a8eb4c6b87604/underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py#L248)):*
> ```Python
>         x_trj = np.random.randn(N, n_x)
> 
>         # reset the regu back to 100 (not 0.0)
> ```

this looks like it changes it to zero, not 100?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice and @RussTedrake)

___
*[underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py, line 248 at r3](https://reviewable.io/reviews/russtedrake/underactuated/486#-My8yVDTAzyPe9YfVz0O:-My9Damf6U_CLefxzsG7:b-uid7zv) ([raw file](https://github.com/russtedrake/underactuated/blob/d2b9b7bc1b170ef2941b4f84524a8eb4c6b87604/underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py#L248)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this looks like it changes it to zero, not 100?
</blockquote></details>

The comment is there for if/when we want to change this back to test for the difference between the two implementations we discussed. Setting regu to 0.0 ensures that the two implementations are equivalent. I can remove the comment if you like

**Comment by RussTedrake** [comment]
___
*[underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py, line 248 at r3](https://reviewable.io/reviews/russtedrake/underactuated/486#-My8yVDTAzyPe9YfVz0O:-MyA7y5z3NrBPO-FqxFi:bzc4lfm) ([raw file](https://github.com/russtedrake/underactuated/blob/d2b9b7bc1b170ef2941b4f84524a8eb4c6b87604/underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py#L248)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The comment is there for if/when we want to change this back to test for the difference between the two implementations we discussed. Setting regu to 0.0 ensures that the two implementations are equivalent. I can remove the comment if you like
</blockquote></details>

I see.  So can you write TODO(AlexandreAmice) here?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice and @RussTedrake)

___
*[underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py, line 248 at r3](https://reviewable.io/reviews/russtedrake/underactuated/486#-My8yVDTAzyPe9YfVz0O:-MyA9KOR8lam5wt4rYdv:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/d2b9b7bc1b170ef2941b4f84524a8eb4c6b87604/underactuated/exercises/trajopt/ilqr_driving/test_ilqr_driving.py#L248)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I see.  So can you write TODO(AlexandreAmice) here?  
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/486#-:-MyAP4mdBxILZ5MTpCQu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

**Pull request merged**
