### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Use relative imports

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/216)

### CODE REVIEW

**Comment by RussTedrake** [comment]
LGTM once CI is happy

can you please also update the installation instructions in underactuated.html to use python 3?

**Comment by EricCousineau-TRI** [comment]
Done, I think. Also, forgot that this would remove support for Xenial, since Python 3 is not supported there :(

There are ways around it, but it'd be pouring effort into something that'd be going away per timeline in https://github.com/RobotLocomotion/drake/issues/10606

**Comment by RussTedrake** [comment]
Ah.  That’s not as good.

Do the changes to the python code actually break python 2 support?  Can we land the changes and just update the bionic to use python3 but leave xenial there using python2?

I have a nightly xenial build on CI still.

**Comment by EricCousineau-TRI** [comment]
> Do the changes to the python code actually break python 2 support?

I don't think so; will try to fix it up later today.

That being said, can I ask if keeping Xenial support around is for supporting students who don't have time to upgrade to Bionic on their host machines, given that `underactuated` and `manipulation` both encourage Docker-based workflows that can just use Bionic?
(If so, then yeah, I'm cool with that; just wanna check.)

**Comment by RussTedrake** [comment]
i agree that students mostly use the docker workflow.  and i'll work to transition away from python2 / xenial.  but even i need a little transition time, and i think some folks in RLG might, too.

**Comment by RussTedrake** [comment]
btw -- CI is still broken.  but you've started me back on converting to python3, so now I'm keen to land this.  That's assuming the python changes are good for both, the xenial installation procedure basically doesn't change -- so still works with 2.7, and the bionic gets updated to 3.6.  If that doesn't pan out, then we'll have to make the harder decision.

**Comment by RussTedrake** [comment]
fyi -- hoping to land this soon; (sadly) it's blocking pushing more tutorials to drake.

**Comment by EricCousineau-TRI** [comment]
Aye, will try for 30min to try and support both 2.7 on Xenial on 3.x on Bionic / Mac.

> [...] it's blocking pushing more tutorials to drake.

Er, I'm not sure if I understand how this is blocking migration?

**Comment by RussTedrake** [comment]
@hongkai-dai is writing tutorials for mathematical program (in python3 since you upgraded him).  but the colab setup scripts still use the jupyter-setup scripts in this repo.  obviously... we need to fix that, too.

**Comment by RussTedrake** [comment]
i don't have an easy way to trigger the circle ci xenial build I'm afraid... but it will run on nightly.

**Comment by RussTedrake** [comment]
just manually retriggered CI

**Comment by RussTedrake** [comment]
still fails on the deprecation warning (master is failing on that).  but i am going to pull the trigger and resolve that on a follow-up PR.

**Comment by EricCousineau-TRI** [comment]
___
*[figures/quadrotor2d.svg, line 1 at r1](https://reviewable.io/reviews/russtedrake/underactuated/216#-Lh3-QA01ReDW6bP3hyD:-LhBXvYIE6MWa_ww0iWt:b-lkrz5i) ([raw file](https://github.com/russtedrake/underactuated/blob/16cad5e3af19e0eac0b043ff78b6320a4c6ec5c3/figures/quadrotor2d.svg#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

file is still here?
</blockquote></details>

I think reviewable was just showing the same file, but no changes? (across base + r2?)

**Comment by EricCousineau-TRI** [comment]
Added deprecation fix in hotfix (#221)

**Pull request merged**
