### PR TITLE
prefer context.SetContinuousState

### PR DESCRIPTION
**Pull request by RussTedrake**

### CODE REVIEW

**Comment by RussTedrake** [comment]
___
*[src/acrobot/dircol_swingup.py, line 14 at r1](https://reviewable.io/reviews/russtedrake/underactuated/166#-LZJvp9h7QvzNaO5rPOV:-LZJvp9h7QvzNaO5rPOW:b4e9wnd) ([raw file](https://github.com/russtedrake/underactuated/blob/5cdc6706c4a0467aa767002b81bc534eea65a3f0/src/acrobot/dircol_swingup.py#L14)):*
> ```Python
> context = plant.CreateDefaultContext()
> 
> dircol = DirectCollocation(plant, context, num_time_samples=25,
> ```

@hongkai-dai -- I don't know why I needed to change this.  without it, snopt failed to solve the problem.  (it was working before the API change to Solve... I think.  disclaimer: i also don't actually know why my CI did not catch the Solve API change... i only found it when running tests on my local machine).

you would expect my SetInitialTrajectory methods to still be working, correct?  Anything else change in this go-around?  (snopt version?)

**Comment by RussTedrake** [comment]
Yes.  Snopt.  I build and install directly with bazel from my main drake tree.  (There is a bazel install rule)

**Comment by RussTedrake** [comment]
@hongkai-dai -- I've split out the acrobot issue into it's own PR: https://github.com/RussTedrake/underactuated/pull/168

**Comment by hongkai-dai** [comment]
Sorry for being slow on this one. I tried to build the drake python binding through either cmake or bazel, but I cannot run python binding succesfully in underactuated repo with either build. I posted the question on slack channel but haven't resolved it yet.

**Pull request merged**
