### PR TITLE
iLQR theory written assignment

### PR DESCRIPTION
**Pull request by iamsavva**
theory iLQR assignment. I updated the references, the paper should be cited properly.

Russ, are there any additional questions you'd like to add here?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @iamsavva)

___
*[`book/trajopt.html` line 1469 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcVuBK43woU5YmtmvG:-NtcVuBK43woU5YmtmvH:b-766y5x) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1469)):*
> ```HTML
>         Please read sections 1 and 2 of this paper <elib>Nganga21</elib>, paying close attention to section 2 in particular. 
>         Then answer the following questions in your own words. 
>         Please refrain from submitting hand-written responses; 1-3 sentences per part would suffice.
> ```

it's a little strange to say this in the "book".  and how are they supposed to submit their responses, if not hand-written?
___
*[`book/trajopt.html` line 1474 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcW7hv9Mj58DtWmkmt:-NtcW7hv9Mj58DtWmkmu:b9qqjd6) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1474)):*
> ```HTML
>       <ol type="a">
> 
>         <li>Explain what problem iLQR is solving.</li>
> ```

it's a bit vague/open-ended.  perhaps that's ok...

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550)* status: all files reviewed, 2 unresolved discussions (waiting on @iamsavva)

**Review by iamsavva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @RussTedrake)

___
*[`book/trajopt.html` line 1469 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcVuBK43woU5YmtmvG:-NtdVk_UEiXqsG5XiAUw:b5uokc) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1469)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's a little strange to say this in the "book".  and how are they supposed to submit their responses, if not hand-written?
</blockquote></details>

certainly; this was meant more so to encourage word / latex responses; I will remove that.
___
*[`book/trajopt.html` line 1474 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcW7hv9Mj58DtWmkmt:-NtdVz7P5SnV6QAtPvlI:b-jl7nts) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1474)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's a bit vague/open-ended.  perhaps that's ok...
</blockquote></details>

I'll reword to make this more specific.

**Review by iamsavva — COMMENTED** [review]
fixed both requests

> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550#-:-NtdWsST4hAabYF12TRM:blbi9pu)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @RussTedrake)

**Review by iamsavva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/underactuated/550)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @RussTedrake)

___
*[`book/trajopt.html` line 1469 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcVuBK43woU5YmtmvG:-NtdXgBq2lHAJp7glvVn:bujqfi5) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1469)):*
<details><summary><i>Previously, iamsavva (Savva Morozov) wrote…</i></summary><blockquote>

certainly; this was meant more so to encourage word / latex responses; I will remove that.
</blockquote></details>

resolved
___
*[`book/trajopt.html` line 1474 at r1](https://reviewable.io/reviews/RussTedrake/underactuated/550#-NtcW7hv9Mj58DtWmkmt:-NtdXk2E2qGnPwu9IqE0:bujqfi5) ([raw file](https://github.com/RussTedrake/underactuated/blob/7539e87c5a7211b785f390ed69a130d9c94e1290/book/trajopt.html#L1474)):*
<details><summary><i>Previously, iamsavva (Savva Morozov) wrote…</i></summary><blockquote>

I'll reword to make this more specific.
</blockquote></details>

resolved

**Pull request merged**
