### PR TITLE
clarify zmp question

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/490)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[humanoids.html, line 412 at r1](https://reviewable.io/reviews/russtedrake/underactuated/490#-N-yV-Zv0Q1b8vqTMMqB:-N-yV-Zv0Q1b8vqTMMqC:bs9u5kz) ([raw file](https://github.com/russtedrake/underactuated/blob/86c5a4c0d0b562d959f1a8db16228479b12348ee/humanoids.html#L412)):*
> ```HTML
> 
>        <li>
>          Suppose you are designing a foot that maximizes the postures you can assume without falling down. Assume the ankle joint is sufficiently actuated to cancel gravity. <ol type = i>
> ```

could be more clear to say "we can apply a torque at the ankle, without torque limits".

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/490)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[humanoids.html, line 412 at r1](https://reviewable.io/reviews/russtedrake/underactuated/490#-N-yV-Zv0Q1b8vqTMMqB:-N-ygtZIBrjZ_pGAgWKo:b-896fix) ([raw file](https://github.com/russtedrake/underactuated/blob/86c5a4c0d0b562d959f1a8db16228479b12348ee/humanoids.html#L412)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

could be more clear to say "we can apply a torque at the ankle, without torque limits".
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/490#-:-N-yylinAaqajqWOJjJw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/underactuated/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
